name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2.4.4
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: |
        npm ci
    - name: Lint code
      run: |
        npm run lint