name: Staging Deployment to AWS CodeDeploy

on:
  push:
    branches: [main, cd-testing]
  pull_request:
    branches: [main, cd-testing]

jobs:
  aws_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli

      # - name: Configure AWS credentials
      #   run: |
      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws configure set default.region ${{ secrets.AWS_REGION }}

      # - name: Deploy to Elastic Beanstalk
      #   run: |
      #     aws elasticbeanstalk create-application-version --application-name my-app \
      #       --version-label ${{ github.sha }} \
      #       --source-bundle S3Bucket=my-bucket,S3Key=my-app.zip
      #     aws elasticbeanstalk update-environment --environment-name my-env \
      #       --version-label ${{ github.sha }}
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: eu-west-2
      # - name: Install AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y python3-pip
      #     pip3 install awscli --upgrade --user
      # - name: Deploy to AWS CodeDeploy
      #   run: |
      #     aws deploy create-deployment \
      #       --application-name gitploy \
      #       --deployment-group-name eantypas \
      #       --revision revisionType=GitHub,repository=${{ github.repository }},commitId=${{ github.sha }} \
      #       --region eu-west-2