name: Staging Deployment to Google Cloud Build

on:
  push:
    branches: [main, cd-testing]
  pull_request:
    branches: [main, cd-testing]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_email: ${{ env.SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
      - name: Build and deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/gitploy --substitutions _ENVIRONMENT=staging,\
          _REGION=europe-west2 --project ${{ env.PROJECT_ID }} https://github.com/eantypas/gitploy.git
          gcloud run deploy gitploy --image gcr.io/${{ env.PROJECT_ID }}/gitploy --platform managed --region europe-west2

