name: Deploy to GCP

on:
  push:
    branches: [main, cd-testing]
  pull_request:
    branches: [main, cd-testing]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
      - name: Build and deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/gitploy
          gcloud run deploy gitploy --image gcr.io/${{ secrets.PROJECT_ID }}/gitploy --platform managed --region europe-west3
