name: Deploy to Docker Containers

on:
  push:
    branches:
      - main

jobs:
  docker_staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}

      # - name: Deploy to staging environment
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.STAGING_SERVER }}
      #     username: ${{ secrets.STAGING_USERNAME }}
      #     key: ${{ secrets.STAGING_SSH_KEY }}
      #     script: |
      #       docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}
      #       docker stop ${{ secrets.DOCKER_REPOSITORY }} || true
      #       docker rm ${{ secrets.DOCKER_REPOSITORY }} || true
      #       docker run -d --name ${{ secrets.DOCKER_REPOSITORY }} -p 80:80 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}