name: Deploy to AWS CodeDeploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: eu-west-2
      # - name: Install AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y python3-pip
      #     pip3 install awscli --upgrade --user
      # - name: Deploy to AWS CodeDeploy
      #   run: |
      #     aws deploy create-deployment \
      #       --application-name MyApp \
      #       --deployment-group-name MyDeploymentGroup \
      #       --revision revisionType=GitHub,repository=${{ github.repository }},commitId=${{ github.sha }} \
      #       --region eu-west-2