name: Deploy to GCP

on:
  push:
    branches: [main, cd-testing]
  pull_request:
    branches: [main, cd-testing]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        
    - name: Build and Deploy to Cloud Run
      id: deploy-cloud-run
      uses: GoogleCloudPlatform/cloud-builders/gcloud@master
      with:
        args: ['run', 'deploy', 'gitops', '--image', 'gcr.io/${{ secrets.GCP_PROJECT_ID }}/image-1', '--platform', 'managed', '--region', 'europe-west3
']

    - name: Get Cloud Run Service URL
      run: echo ::set-env name=SERVICE_URL::$(gcloud run services describe gitops --platform managed --region europe-west3 --format 'value(status.url)')

    # - name: Update App with New Service URL
    #   run: |
    #     # Use $SERVICE_URL variable to update your application with the new Cloud Run service URL.
